#!/usr/bin/env node

import {readFile, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import ts from 'typescript';

const inputUrl = new URL('./node_modules/@paulirish/trace_engine/models/trace/types/TraceEvents.d.ts', import.meta.url);
const outputUrl = new URL('./gen/trace-event-factories.ts', import.meta.url);

type InterfaceDefinition = {
  parents: string[];
  literals: Map<string, string>;
};

function propertyName(member: ts.PropertySignature): string | undefined {
  return member.name && ts.isIdentifier(member.name) ? member.name.text : undefined;
}

function literalInitializer(type: ts.TypeNode): string | undefined {
  if (ts.isLiteralTypeNode(type) && (ts.isStringLiteral(type.literal) || ts.isNoSubstitutionTemplateLiteral(type.literal))) {
    return JSON.stringify(type.literal.text);
  }
  if (ts.isTypeReferenceNode(type) && ts.isQualifiedName(type.typeName)) {
    const owner = type.typeName.left;
    if (ts.isIdentifier(owner) && (owner.text === 'Phase' || owner.text === 'Name')) {
      return `TraceEvents.${owner.text}.${type.typeName.right.text}`;
    }
  }
  return undefined;
}

/** Parse trace interfaces with TypeScript's parser instead of interpreting declaration text. */
export function parseInterfaces(source: string): Map<string, InterfaceDefinition> {
  const sourceFile = ts.createSourceFile('TraceEvents.d.ts', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const interfaces = new Map<string, InterfaceDefinition>();

  for (const statement of sourceFile.statements) {
    if (!ts.isInterfaceDeclaration(statement)) continue;
    const parents = statement.heritageClauses
      ?.filter(clause => clause.token === ts.SyntaxKind.ExtendsKeyword)
      .flatMap(clause => clause.types)
      .map(parent => ts.isIdentifier(parent.expression) ? parent.expression.text : undefined)
      .filter((parent): parent is string => Boolean(parent)) ?? [];
    const literals = new Map<string, string>();
    for (const member of statement.members) {
      if (!ts.isPropertySignature(member) || !member.type) continue;
      const name = propertyName(member);
      if (name !== 'cat' && name !== 'name' && name !== 'ph') continue;
      const initializer = literalInitializer(member.type);
      if (initializer) literals.set(name, initializer);
    }
    interfaces.set(statement.name.text, {parents, literals});
  }
  return interfaces;
}

function lowerFirst(value: string): string {
  return value[0].toLowerCase() + value.slice(1);
}

export function generate(source: string): string {
  const interfaces = parseInterfaces(source);
  const isEvent = (name: string, seen = new Set<string>()): boolean => {
    if (name === 'Event') return true;
    if (seen.has(name)) return false;
    seen.add(name);
    return interfaces.get(name)?.parents.some(parent => isEvent(parent, seen)) ?? false;
  };
  const defaultsFor = (name: string): Map<string, string> => {
    const definition = interfaces.get(name);
    if (!definition) return new Map();
    const defaults = new Map<string, string>();
    for (const parent of definition.parents) {
      for (const [key, value] of defaultsFor(parent)) defaults.set(key, value);
    }
    for (const [key, value] of definition.literals) defaults.set(key, value);
    return defaults;
  };

  const declarations: string[] = [];
  for (const [name] of interfaces) {
    if (!isEvent(name)) continue;
    const functionName = lowerFirst(name);
    const defaults = defaultsFor(name);
    const keys = [...defaults.keys()];
    const initType = keys.length
      ? `Omit<TraceEvents.${name}, ${keys.map(key => `'${key}'`).join(' | ')}> & Partial<Pick<TraceEvents.${name}, ${keys.map(key => `'${key}'`).join(' | ')}>>`
      : `TraceEvents.${name}`;
    declarations.push(`/** Create a \`${name}\` trace event. */\nexport function ${functionName}(init: ${initType}): TraceEvents.${name} {\n  return {\n    ...init,${[...defaults].map(([key, value]) => `\n    ${key}: ${value},`).join('')}\n  } as TraceEvents.${name};\n}`);
  }

  return `// Generated by generate-trace-events.ts. Do not edit by hand.\n` +
    `import * as TraceEvents from '@paulirish/trace_engine/models/trace/types/TraceEvents.js';\n\n` +
    declarations.join('\n\n') + '\n';
}

export async function main(): Promise<void> {
  const source = await readFile(inputUrl, 'utf8');
  await writeFile(outputUrl, generate(source));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
